[workspace]
resolver = "2"
members = ["noir-r1cs", "delegated-spartan", "merkle-hash-bench"]

[workspace.package]
edition = "2021"
rust-version = "1.85"
authors = [
    "Remco Bloemen <remco@world.org>",
    "Philipp Sippl <philipp@world.org>",
]
license = "MIT"
homepage = "https://github.com/worldfnd/ProveKit"
repository = "https://github.com/worldfnd/ProveKit"

[workspace.lints.rust]
unsafe_code = "warn"
missing_docs = "warn"

[workspace.lints.clippy]
all = "warn"
pendatic = "warn"
nursery = "warn"
cargo = "warn"
perf = "warn"
complexity = "warn"
style = "warn"
correctness = "warn"
restriction = "warn"
suspicous = "warn"

[profile.release]
debug = true # Generate symbol info for profiling

# Doing light optimizations helps test performance more than it hurts build time.
[profile.test]
opt-level = 2

# Compilation profile for any non-workspace member. We want to optimize these even in debug mode.
[profile.dev.package."*"]
opt-level = 3
