[package]
name = "merkle-hash-bench"
version = "0.1.0"
edition = "2021"

[dependencies]
arrayvec = "0.7.6"
blake3 = "1.5.4"
bytemuck = "1.19.0"
p3-bn254-fr = { version = "0.2.0", features = ["table"] }
p3-field = "0.2.0"
p3-poseidon2 = "0.2.0"
p3-symmetric = "0.2.0"
rand = "0.8.5"
